version: "3.5"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: flaresolverr/flaresolverr:latest
    environment:
      - PORT=8080
      #- LOG_LEVEL=info
      #- LOG_HTML=false
      #- CAPTCHA_SOLVER=none
      #- BROWSER_TIMEOUT=40000
    restart: unless-stopped
  backend:
    build: backend
    ports:
      - 127.0.0.1:1234:8080
    restart: unless-stopped
    depends_on:
      - flaresolverr
    environment:
      - PROXY
